# AIT8428 Platform Support

#snd-soc-ait-pcm-objs := vsnv3-i2s-pcm.o
#snd-soc-ait_ssc_dai-objs := ait_ssc_dai.o

#obj-$(CONFIG_SND_MCRV2_SOC_ALSA) += snd-soc-ait-pcm.o

#obj-$(CONFIG_SND_MCRV2_SOC_AIT8455_WM8973) += ait8455evb_i2s_wm8973.o
#obj-$(CONFIG_SND_MCRV2_SOC_AIT8455_RT5627) += ait8455evb_i2s_rt5627.o

# AIT8455 Machine Support
obj-$(CONFIG_SND_MCRV2_SOC_ALSA) += ait_afe_dai.o ait_evb_afe.o ait-afe-pcm.o
obj-$(CONFIG_SND_MCRV2_SOC_ALSA_ALG_ENH) += ait_afe_dai.o ait_evb_afe.o ait-afe-pcm-ex.o audio-ring-buf.o aec-work-queue.o
#obj-$(CONFIG_SND_MCRV2_SOC_ALSA) += ait8428evb_i2s.o ait8428-i2s-pcm.o ait_i2s_dai.o


#SOC I2S Driver Added by Vincent Chen#
obj-$(CONFIG_SND_MCRV2_SOC_I2S) += mcrv2-soc-audio.o mcrv2-i2s.o mcrv2-i2s-pcm.o

